name: iOS â€“ PR check

on:
  pull_request:
    types: [ opened, synchronize ]
    paths:
      - 'ios/**'
      - 'shared/**'
      - '.github/workflows/an_pr_build.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on:
      group: matee-tartelets
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          clean: false
      - name: Setup Tools
        working-directory: ios
        run: |
          ./scripts/setup.sh
      - name: Run tests
        working-directory: ios
        run: fastlane test_alpha
